base-url:
  context: /aggregator

log:
  identifierKey: UUID

external-urls:
  product-catalog:
    matching-products: http://localhost:8080/aggregator/catalog/matchingProducts
    preferred-product: http://localhost:8080/aggregator/catalog/prefferdProduct

  feature-detection: http://localhost:8080/aggregator/features/find