base-url:
  context: /best-deal/aggregator/v1

log:
  identifierKey: UUID

external-urls:
  product-catalog:
    matching-products: http://localhost:8080/aggregator/catalog/matchingProducts
    preferred-product: http://localhost:8080/aggregator/catalog/prefferdProduct

  feature-detection: http://localhost:8085/best-deal/cloud-api/v1/vision/product-detect